export const cards = [
  {
    id: "csr",
    name: "Chase Sapphire Reserve",
    shortName: "CSR",
    owner: "patrick",
    color: "#0a4fa8",
    network: "Visa",
    annualFee: 550,
    annualFeeDate: "Check statement",
    categories: [
      { label: "Chase Travel (portal)", multiplier: "8x", points: true },
      { label: "Flights & hotels booked direct", multiplier: "4x", points: true },
      { label: "Dining", multiplier: "3x", points: true },
      { label: "All other purchases", multiplier: "1x", points: true },
    ],
    benefits: [
      {
        label: "$300 Annual Travel Credit",
        description: "Automatically applied to travel purchases each cardmember year.",
        category: "credit",
        expiry: null,
      },
      {
        label: "Priority Pass Lounge Access",
        description: "Unlimited visits for cardholder + 2 guests at 1,300+ airport lounges worldwide.",
        category: "travel",
        expiry: null,
      },
      {
        label: "Global Entry / TSA PreCheck Credit",
        description: "Up to $100 credit every 4 years.",
        category: "credit",
        expiry: null,
      },
      {
        label: "Trip Delay / Cancellation Insurance",
        description: "Up to $500 per ticket for delays over 6 hours, up to $10,000 per trip cancellation.",
        category: "protection",
        expiry: null,
      },
      {
        label: "Primary Rental Car Insurance",
        description: "Collision damage waiver on rental cars worldwide.",
        category: "protection",
        expiry: null,
      },
      {
        label: "DoorDash DashPass",
        description: "Complimentary DashPass membership while enrolled.",
        category: "dining",
        expiry: null,
      },
    ],
    redemptionTip: "Points worth 1.5¢ each via Chase Travel portal. Transfer to United, Hyatt, Marriott, and more at 1:1.",
  },
  {
    id: "hilton",
    name: "Hilton Honors Amex",
    shortName: "Hilton",
    owner: "tbd",
    color: "#003087",
    network: "Amex",
    annualFee: 0,
    annualFeeDate: null,
    categories: [
      { label: "Hilton properties", multiplier: "7x", points: true },
      { label: "Dining at US restaurants", multiplier: "5x", points: true },
      { label: "US supermarkets & gas stations", multiplier: "3x", points: true },
      { label: "All other purchases", multiplier: "3x", points: true },
    ],
    benefits: [
      {
        label: "Hilton Honors Silver Status",
        description: "Automatic Silver status with free weekend night certificate upon spend threshold.",
        category: "status",
        expiry: null,
      },
    ],
    redemptionTip: "Hilton points are best redeemed for free night awards at premium properties.",
  },
  {
    id: "marriott",
    name: "Marriott Bonvoy Boundless",
    shortName: "Marriott",
    owner: "tbd",
    color: "#8b1a1a",
    network: "Visa",
    annualFee: 95,
    annualFeeDate: "Check statement",
    categories: [
      { label: "Marriott Bonvoy hotels", multiplier: "17x", points: true },
      { label: "Groceries, gas & dining", multiplier: "3x", points: true },
      { label: "All other purchases", multiplier: "2x", points: true },
    ],
    benefits: [
      {
        label: "Free Night Award (annually)",
        description: "One free night certificate each account anniversary (up to 35,000 points).",
        category: "hotel",
        expiry: "Anniversary date — use within 12 months",
      },
      {
        label: "Marriott Bonvoy Silver Elite Status",
        description: "Automatic Silver Elite status.",
        category: "status",
        expiry: null,
      },
      {
        label: "15 Elite Night Credits",
        description: "Each calendar year toward higher status.",
        category: "status",
        expiry: "Dec 31 each year",
      },
    ],
    redemptionTip: "Best value: redeem points at Marriott/Ritz-Carlton premium properties or transfer to airlines.",
  },
  {
    id: "united",
    name: "United MileagePlus Card",
    shortName: "United",
    owner: "tbd",
    color: "#004b87",
    network: "Visa",
    annualFee: 95,
    annualFeeDate: "Check statement",
    categories: [
      { label: "United purchases", multiplier: "2x", points: true },
      { label: "Dining", multiplier: "2x", points: true },
      { label: "Hotel stays", multiplier: "2x", points: true },
      { label: "All other purchases", multiplier: "1x", points: true },
    ],
    benefits: [
      {
        label: "Free First Checked Bag",
        description: "Free checked bag for cardholder + 1 companion on same reservation.",
        category: "travel",
        expiry: null,
      },
      {
        label: "Priority Boarding",
        description: "Board in Zone 2 on United flights.",
        category: "travel",
        expiry: null,
      },
      {
        label: "25% Back on In-Flight Purchases",
        description: "Statement credit on food, beverages, and Wi-Fi on United flights.",
        category: "credit",
        expiry: null,
      },
      {
        label: "2 United Club One-Time Passes",
        description: "Each year upon account anniversary.",
        category: "travel",
        expiry: "Anniversary date",
      },
    ],
    redemptionTip: "Miles best used for United saver awards or transfer partners.",
  },
  {
    id: "discover",
    name: "Discover it",
    shortName: "Discover",
    owner: "tbd",
    color: "#f76f20",
    network: "Discover",
    annualFee: 0,
    annualFeeDate: null,
    categories: [
      { label: "Rotating quarterly categories (up to $1,500)", multiplier: "5x", points: false },
      { label: "All other purchases", multiplier: "1x", points: false },
    ],
    benefits: [
      {
        label: "Cashback Match (first year)",
        description: "Discover matches all cashback earned at end of first year.",
        category: "credit",
        expiry: "First cardmember year only",
      },
      {
        label: "No Foreign Transaction Fees",
        description: "Use internationally without fees.",
        category: "travel",
        expiry: null,
      },
    ],
    redemptionTip: "Cashback — good for rotating category maximization (gas, groceries, restaurants, Amazon rotate quarterly).",
  },
  {
    id: "ihg",
    name: "IHG One Rewards Premier",
    shortName: "IHG",
    owner: "tbd",
    color: "#005eb8",
    network: "Visa",
    annualFee: 99,
    annualFeeDate: "Check statement",
    categories: [
      { label: "IHG hotels", multiplier: "26x", points: true },
      { label: "Dining & gas stations", multiplier: "5x", points: true },
      { label: "All other purchases", multiplier: "3x", points: true },
    ],
    benefits: [
      {
        label: "Annual Free Night (up to 40k pts)",
        description: "One free night certificate each anniversary year.",
        category: "hotel",
        expiry: "Anniversary date — use within 12 months",
      },
      {
        label: "IHG Platinum Elite Status",
        description: "Automatic Platinum Elite status.",
        category: "status",
        expiry: null,
      },
      {
        label: "Fourth Night Free on Awards",
        description: "When you redeem points for 4+ consecutive nights, get the 4th night free.",
        category: "hotel",
        expiry: null,
      },
      {
        label: "Global Entry / TSA PreCheck Credit",
        description: "Up to $100 every 4 years.",
        category: "credit",
        expiry: null,
      },
    ],
    redemptionTip: "Best for IHG/InterContinental/Kimpton properties. 4th night free is a strong value play.",
  },
  {
    id: "ink",
    name: "Ink Business Preferred",
    shortName: "Ink Biz",
    owner: "patrick",
    color: "#0a4fa8",
    network: "Visa",
    annualFee: 95,
    annualFeeDate: "Check statement",
    categories: [
      { label: "Travel, shipping, internet, phone, advertising (first $150k)", multiplier: "3x", points: true },
      { label: "All other purchases", multiplier: "1x", points: true },
    ],
    benefits: [
      {
        label: "Cell Phone Protection",
        description: "Up to $1,000 per claim, $100 deductible, when you pay your bill with the card.",
        category: "protection",
        expiry: null,
      },
      {
        label: "Trip Cancellation / Interruption Insurance",
        description: "Up to $5,000 per trip.",
        category: "protection",
        expiry: null,
      },
      {
        label: "Primary Rental Car Insurance (business)",
        description: "Primary coverage when renting for business purposes.",
        category: "protection",
        expiry: null,
      },
    ],
    redemptionTip: "Chase Ultimate Rewards points — transfer to same partners as CSR at 1:1. Combine points with CSR for 1.5¢ redemptions.",
  },
];
