export const cards = [
  {
    id: "csr",
    name: "Chase Sapphire Reserve",
    shortName: "CSR",
    owner: "joint",
    color: "#0a4fa8",
    network: "Visa",
    annualFee: 550,
    annualFeeDate: "August 5",
    annualFeeMonth: 8,
    categories: [
      { label: "Chase Travel (portal)", multiplier: "8x", rate: 8, points: true, tags: ["travel-portal"] },
      { label: "Flights & hotels booked direct", multiplier: "4x", rate: 4, points: true, tags: ["flights", "hotels-direct"] },
      { label: "Dining", multiplier: "3x", rate: 3, points: true, tags: ["dining"] },
      { label: "All other purchases", multiplier: "1x", rate: 1, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "$300 Annual Travel Credit", description: "Automatically applied to travel purchases each cardmember year.", category: "credit", expiry: null },
      { label: "Priority Pass Lounge Access", description: "Unlimited visits for cardholder + 2 guests at 1,300+ airport lounges worldwide.", category: "travel", expiry: null },
      { label: "Global Entry / TSA PreCheck Credit", description: "Up to $100 credit every 4 years.", category: "credit", expiry: null },
      { label: "Trip Delay / Cancellation Insurance", description: "Up to $500 per ticket for delays over 6 hours, up to $10,000 per trip cancellation.", category: "protection", expiry: null },
      { label: "Primary Rental Car Insurance", description: "Collision damage waiver on rental cars worldwide.", category: "protection", expiry: null },
      { label: "DoorDash DashPass", description: "Complimentary DashPass membership while enrolled.", category: "dining", expiry: null },
    ],
    redemptionTip: "Points worth 1.5¢ each via Chase Travel portal. Transfer to United, Hyatt, Marriott, and more at 1:1.",
    playbook: {
      title: "First Renewal — Retention Bonus or Downgrade Strategy",
      context: "This is your first renewal cycle. The $550 fee posts August 5th. Chase gives you exactly 30 days to cancel or downgrade for a full refund. Here's how to play it.",
      effectiveCost: "Net cost after $300 travel credit = $250/yr — worth it only if you use Priority Pass lounges or book significant travel.",
      steps: [
        {
          timing: "Aug 5 — Fee Posts",
          label: "Do NOT call yet",
          detail: "Your $300 annual travel credit resets on the first statement after your anniversary. Call too early and you risk forfeiting the new credit. Wait for it to appear in your account.",
          type: "warning",
        },
        {
          timing: "Aug 5–12",
          label: "Spend the $300 travel credit immediately",
          detail: "Book anything that codes as travel — flights, hotels, Uber, transit passes, parking. Chase auto-applies the credit to your statement. Historically they do not claw it back if you later cancel or downgrade.",
          type: "action",
        },
        {
          timing: "Aug 12–28",
          label: "Call Chase and ask for a retention offer",
          detail: "Call the number on the back of the card and say: \"I'm considering canceling due to the annual fee. Are there any retention offers available?\" Chase commonly offers 10,000–50,000 bonus points or a statement credit. If the offer covers $100+, it likely makes sense to keep the card another year.",
          type: "action",
        },
        {
          timing: "By Sep 4 — Hard Deadline",
          label: "Decide: keep, downgrade, or cancel",
          detail: "Chase's strict window is 30 days from the fee posting date (Aug 5 + 30 days = Sep 4). After that, you will NOT get a refund. Options: (1) Keep it if the retention offer was good. (2) Downgrade to Chase Sapphire Preferred ($95/yr) — you keep your points and account history. (3) Cancel entirely for a full $550 refund.",
          type: "deadline",
        },
        {
          timing: "If downgrading",
          label: "Downgrade to Sapphire Preferred, not a no-fee card",
          detail: "Downgrading to CSP ($95/yr) keeps your Ultimate Rewards points alive and preserves your account age (good for credit score). Canceling entirely kills your UR points if you have no other Chase card. The Ink Business Preferred can hold UR points as a fallback.",
          type: "tip",
        },
      ],
    },
  },
  {
    id: "hilton",
    name: "Hilton Honors Surpass",
    shortName: "Hilton",
    owner: "michael anne",
    color: "#003087",
    network: "Amex",
    annualFee: 150,
    annualFeeDate: "June 12",
    annualFeeMonth: 6,
    categories: [
      { label: "Hilton properties", multiplier: "12x", rate: 12, points: true, tags: ["hotels-brand"] },
      { label: "Dining at US restaurants", multiplier: "6x", rate: 6, points: true, tags: ["dining"] },
      { label: "US supermarkets & gas stations", multiplier: "4x", rate: 4, points: true, tags: ["groceries", "gas"] },
      { label: "All other purchases", multiplier: "3x", rate: 3, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "Hilton Honors Gold Status", description: "Automatic Gold status — includes room upgrades, free breakfast at many properties, and bonus points.", category: "status", expiry: null },
      { label: "Free Weekend Night Certificate", description: "Earn one free weekend night after spending $15,000 in a calendar year.", category: "hotel", expiry: "Calendar year" },
      { label: "Priority Pass (10 visits/yr)", description: "10 complimentary lounge visits per year through Priority Pass.", category: "travel", expiry: null },
    ],
    redemptionTip: "Hilton points best redeemed for free night awards at premium properties. Gold status makes this card strong for frequent Hilton stays.",
  },
  {
    id: "marriott",
    name: "Marriott Bonvoy Boundless",
    shortName: "Marriott",
    owner: "patrick",
    color: "#8b1a1a",
    network: "Visa",
    annualFee: 95,
    annualFeeDate: "July 1",
    annualFeeMonth: 7,
    categories: [
      { label: "Marriott Bonvoy hotels", multiplier: "17x", rate: 17, points: true, tags: ["hotels-brand"] },
      { label: "Groceries, gas & dining", multiplier: "3x", rate: 3, points: true, tags: ["groceries", "gas", "dining"] },
      { label: "All other purchases", multiplier: "2x", rate: 2, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "Free Night Award (annually)", description: "One free night certificate each account anniversary (up to 35,000 points).", category: "hotel", expiry: "Anniversary date — use within 12 months" },
      { label: "Marriott Bonvoy Silver Elite Status", description: "Automatic Silver Elite status.", category: "status", expiry: null },
      { label: "15 Elite Night Credits", description: "Each calendar year toward higher status.", category: "status", expiry: "Dec 31 each year" },
    ],
    redemptionTip: "Best value: redeem points at Marriott/Ritz-Carlton premium properties or transfer to airlines.",
  },
  {
    id: "united",
    name: "United MileagePlus Card",
    shortName: "United",
    owner: "patrick",
    color: "#004b87",
    network: "Visa",
    annualFee: 95,
    annualFeeDate: "Check statement",
    categories: [
      { label: "United purchases", multiplier: "2x", rate: 2, points: true, tags: ["flights"] },
      { label: "Dining", multiplier: "2x", rate: 2, points: true, tags: ["dining"] },
      { label: "Hotel stays", multiplier: "2x", rate: 2, points: true, tags: ["hotels-direct"] },
      { label: "All other purchases", multiplier: "1x", rate: 1, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "Free First Checked Bag", description: "Free checked bag for cardholder + 1 companion on same reservation.", category: "travel", expiry: null },
      { label: "Priority Boarding", description: "Board in Zone 2 on United flights.", category: "travel", expiry: null },
      { label: "25% Back on In-Flight Purchases", description: "Statement credit on food, beverages, and Wi-Fi on United flights.", category: "credit", expiry: null },
      { label: "2 United Club One-Time Passes", description: "Each year upon account anniversary.", category: "travel", expiry: "Anniversary date" },
    ],
    redemptionTip: "Miles best used for United saver awards or transfer partners.",
  },
  {
    id: "discover",
    name: "Discover it",
    shortName: "Discover",
    owner: "patrick",
    color: "#f76f20",
    network: "Discover",
    annualFee: 0,
    annualFeeDate: null,
    categories: [
      { label: "Rotating quarterly categories (up to $1,500)", multiplier: "5%", rate: 5, points: false, tags: ["dining", "groceries", "gas", "other"] },
      { label: "All other purchases", multiplier: "1%", rate: 1, points: false, tags: ["other"] },
    ],
    benefits: [
      { label: "Cashback Match (first year)", description: "Discover matches all cashback earned at end of first year.", category: "credit", expiry: "First cardmember year only" },
      { label: "No Foreign Transaction Fees", description: "Use internationally without fees.", category: "travel", expiry: null },
    ],
    redemptionTip: "Cashback — good for rotating category maximization (gas, groceries, restaurants, Amazon rotate quarterly).",
  },
  {
    id: "ihg",
    name: "IHG One Rewards Premier",
    shortName: "IHG",
    owner: "patrick",
    color: "#005eb8",
    network: "Visa",
    annualFee: 99,
    annualFeeDate: "November 1",
    annualFeeMonth: 11,
    categories: [
      { label: "IHG hotels", multiplier: "26x", rate: 26, points: true, tags: ["hotels-brand"] },
      { label: "Dining", multiplier: "5x", rate: 5, points: true, tags: ["dining"] },
      { label: "Gas stations", multiplier: "5x", rate: 5, points: true, tags: ["gas"] },
      { label: "All other purchases", multiplier: "3x", rate: 3, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "Annual Free Night (up to 40k pts)", description: "One free night certificate each anniversary year.", category: "hotel", expiry: "Anniversary date — use within 12 months" },
      { label: "IHG Platinum Elite Status", description: "Automatic Platinum Elite status.", category: "status", expiry: null },
      { label: "Fourth Night Free on Awards", description: "When you redeem points for 4+ consecutive nights, get the 4th night free.", category: "hotel", expiry: null },
      { label: "Global Entry / TSA PreCheck Credit", description: "Up to $100 every 4 years.", category: "credit", expiry: null },
    ],
    redemptionTip: "Best for IHG/InterContinental/Kimpton properties. 4th night free is a strong value play.",
  },
  {
    id: "ink",
    name: "Ink Business Preferred",
    shortName: "Ink Biz",
    owner: "patrick",
    color: "#0a4fa8",
    network: "Visa",
    annualFee: 95,
    annualFeeDate: "Check statement",
    categories: [
      { label: "Travel (first $150k/yr)", multiplier: "3x", rate: 3, points: true, tags: ["travel-portal", "flights", "hotels-direct"] },
      { label: "Shipping", multiplier: "3x", rate: 3, points: true, tags: ["shipping"] },
      { label: "Internet, phone & cable", multiplier: "3x", rate: 3, points: true, tags: ["phone"] },
      { label: "Advertising", multiplier: "3x", rate: 3, points: true, tags: ["advertising"] },
      { label: "All other purchases", multiplier: "1x", rate: 1, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "Cell Phone Protection", description: "Up to $1,000 per claim, $100 deductible, when you pay your bill with the card.", category: "protection", expiry: null },
      { label: "Trip Cancellation / Interruption Insurance", description: "Up to $5,000 per trip.", category: "protection", expiry: null },
      { label: "Primary Rental Car Insurance (business)", description: "Primary coverage when renting for business purposes.", category: "protection", expiry: null },
    ],
    redemptionTip: "Chase Ultimate Rewards points — transfer to same partners as CSR at 1:1. Combine points with CSR for 1.5¢ redemptions.",
  },
  {
    id: "venture-x",
    name: "Capital One Venture X",
    shortName: "Venture X",
    owner: "joint",
    color: "#d03027",
    network: "Visa Infinite",
    annualFee: 395,
    annualFeeDate: "Check statement",
    categories: [
      { label: "Capital One Travel portal", multiplier: "10x", rate: 10, points: true, tags: ["travel-portal"] },
      { label: "Hotels & rental cars (Capital One Travel)", multiplier: "5x", rate: 5, points: true, tags: ["hotels-direct"] },
      { label: "All other purchases", multiplier: "2x", rate: 2, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "$300 Annual Travel Credit", description: "$300 back each year on bookings made through Capital One Travel portal.", category: "credit", expiry: "Cardmember year" },
      { label: "10,000 Bonus Miles Anniversary", description: "10,000 miles ($100 value) every year on your account anniversary.", category: "credit", expiry: "Anniversary date" },
      { label: "Capital One Lounge + Priority Pass", description: "Unlimited access to Capital One Lounges + Priority Pass Select (unlimited visits) for cardholder and 2 guests free.", category: "travel", expiry: null },
      { label: "Global Entry / TSA PreCheck Credit", description: "Up to $100 credit every 4 years.", category: "credit", expiry: null },
      { label: "Trip Cancellation / Interruption Insurance", description: "Up to $2,000 per person for prepaid travel.", category: "protection", expiry: null },
      { label: "Primary Rental Car Insurance", description: "Primary collision damage waiver on rental cars.", category: "protection", expiry: null },
      { label: "Cell Phone Protection", description: "Up to $800 per claim when you pay your monthly bill with the card.", category: "protection", expiry: null },
    ],
    redemptionTip: "Miles worth 1¢ each as statement credit, or transfer to 15+ airline/hotel partners (Air Canada, Turkish, Wyndham, etc.) — often 1:1.",
  },
  {
    id: "amex-green",
    name: "American Express Green Card",
    shortName: "Amex Green",
    owner: "patrick",
    color: "#1a8e6f",
    network: "Amex",
    annualFee: 150,
    annualFeeDate: "June 18",
    annualFeeMonth: 6,
    categories: [
      { label: "Travel", multiplier: "3x", rate: 3, points: true, tags: ["travel-portal", "flights", "hotels-direct"] },
      { label: "Transit", multiplier: "3x", rate: 3, points: true, tags: ["gas"] },
      { label: "Dining (incl. delivery & takeout)", multiplier: "3x", rate: 3, points: true, tags: ["dining"] },
      { label: "All other purchases", multiplier: "1x", rate: 1, points: true, tags: ["other"] },
    ],
    benefits: [
      { label: "$100 Annual Travel Credit (CLEAR + LoungeBuddy)", description: "Statement credits for CLEAR Plus membership and LoungeBuddy bookings.", category: "credit", expiry: "Cardmember year" },
      { label: "No Foreign Transaction Fees", description: "Use abroad without extra fees.", category: "travel", expiry: null },
      { label: "Baggage Insurance", description: "Coverage for lost, damaged, or stolen baggage on trips charged to the card.", category: "protection", expiry: null },
    ],
    redemptionTip: "Membership Rewards points — transfer to airline/hotel partners or use Pay With Points. Lower fee than CSR/Venture X but solid 3x on dining, travel, and transit.",
  },
  {
    id: "citi",
    name: "Citi Double Cash",
    shortName: "Citi",
    owner: "patrick",
    color: "#056DAE",
    network: "Mastercard",
    annualFee: 0,
    annualFeeDate: null,
    categories: [
      { label: "All purchases (2% total: 1% on buy + 1% on pay)", multiplier: "2%", rate: 2, points: false, tags: ["dining", "groceries", "gas", "travel-portal", "flights", "hotels-direct", "hotels-brand", "phone", "other"] },
    ],
    benefits: [
      { label: "No Annual Fee", description: "No annual fee — straight 2% cashback on everything.", category: "credit", expiry: null },
      { label: "No Foreign Transaction Fees", description: "Use abroad without extra fees.", category: "travel", expiry: null },
    ],
    redemptionTip: "Simple 2% on everything — best fallback card when no other card earns more than 2x on a category.",
  },
];

// Spending buckets for the "Best Card" summary view
export const spendingBuckets = [
  { tag: "dining",        label: "Dining & Restaurants", icon: "🍽️" },
  { tag: "groceries",     label: "Groceries",            icon: "🛒" },
  { tag: "gas",           label: "Gas",                  icon: "⛽" },
  { tag: "travel-portal", label: "Travel (Portal)",      icon: "🖥️" },
  { tag: "flights",       label: "Flights (Direct)",     icon: "✈️" },
  { tag: "hotels-brand",  label: "Hotels (Brand Site)",  icon: "🏨" },
  { tag: "hotels-direct", label: "Hotels (Direct/Other)", icon: "🛏️" },
  { tag: "phone",         label: "Phone / Internet",     icon: "📱" },
  { tag: "other",         label: "Everything Else",      icon: "💳" },
];
